theme = "slick"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "bluetooth"
mac = "FD:EE:EE:00:06:C3"
format = "S1D {percentage}"
hide_disconnected = true
format_unavailable = "S1D x"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
